### ISSUE TITLE
BSM Node code from Tutorials gives the result that is not affected by seed

### ISSUE THREAD

**Issue by viachesl** [sequence-toolbox/SeQUeNCe#56] opened 2021-01-13 05:03 UTC
Hello!

I'm running the example from Chapter 3 that according to the description should gives different results depending on seed:
```
# (if the generation fails) "after node1.memo {'node_id': None, 'memo_id': None} 0"
# (if the generation succeeds) "after node1.memo {'node_id': 'node2', 'memo_id': 'node2.memo'} 0.9"
```
but in my case it gives only first one all the times. But "running multiple times" ( assign in the code below  'runMultipleTimes = True' ) part do depends on seed. This is the code I run:
```
import sys, time
sys.path.append( '../' )

from sequence.topology.node import Node
from sequence.components.memory import Memory
from sequence.entanglement_management.generation import EntanglementGenerationA
from sequence.kernel.timeline import Timeline
from sequence.topology.node import BSMNode
from sequence.components.optical_channel import QuantumChannel, ClassicalChannel
from sequence.entanglement_management.entanglement_protocol import EntanglementProtocol

import numpy as np

runMultipleTimes = False
__seed = int( time.time() * 1000 ) % 2**32
np.random.seed( __seed )

class SimpleManager():
    def __init__(self):
        self.raw_counter = 0
        self.ent_counter = 0

    def update(self, protocol, memory, state):
        if state == 'RAW':
            self.raw_counter += 1
        else:
            self.ent_counter += 1


class EntangleGenNode(Node):
    def __init__(self, name: str, tl: Timeline):
        super().__init__(name, tl)
        self.memory = Memory('%s.memo'%name, tl, fidelity=0.9, frequency=2000,
                             efficiency=1, coherence_time=-1, wavelength=500 ) #0.9, 2000, 1, -1, 500)
        self.memory.owner = self
        self.resource_manager = SimpleManager()
        self.protocols = []

    def receive_message(self, src: str, msg: "Message") -> None:
        self.protocols[0].received_message(src, msg)

    def create_protocol(self, middle: str, other: str):
        self.protocols = [EntanglementGenerationA(self, '%s.eg'%self.name, middle, other, self.memory)]

def pair_protocol( p1: EntanglementProtocol, p2: EntanglementProtocol ):
    p1.set_others( p2 )
    p2.set_others( p1 )

tl = Timeline()
tl.seed( __seed % 256 )

node1 = EntangleGenNode('node1', tl)
node2 = EntangleGenNode('node2', tl)
bsm_node = BSMNode('bsm_node', tl, ['node1', 'node2'])

bsm_node.bsm.update_detectors_params( 'efficiency', 1 )

qc1 = QuantumChannel( 'qc1', tl, attenuation=0, distance=1000 )
qc2 = QuantumChannel( 'qc2', tl, attenuation=0, distance=1000 )
qc1.set_ends(node1, bsm_node)
qc2.set_ends(node2, bsm_node)

nodes = [ node1, node2, bsm_node ]

for i in range(3):
    for j in range(3):
        if i == j:
            continue
        cc = ClassicalChannel( 'cc_%s_%s' % (nodes[i].name, nodes[j].name),
                               tl, 1000, 1e8 )
        cc.set_ends( nodes[i], nodes[j] )

node1.create_protocol('bsm_node', 'node2')
node2.create_protocol('bsm_node', 'node1')
pair_protocol( node1.protocols[0], node2.protocols[0] )

node1.memory.reset()
node2.memory.reset()

print( 'before', node1.memory.entangled_memory, node1.memory.fidelity )
# "before node1.memo {'node_id': None, 'memo_id': None} 0"

node1.protocols[0].start()
node2.protocols[0].start()

tl.init()
print( 'tl.now() =', tl.now() )
tl.run()

print('after', node1.memory.entangled_memory, node1.memory.fidelity )
print( 'Entanglement succeeded:', bool( node1.resource_manager.ent_counter ), node1.resource_manager.raw_counter )
# (if the generation fails) "after node1.memo {'node_id': None, 'memo_id': None} 0"
# (if the generation succeeds) "after node1.memo {'node_id': 'node2', 'memo_id': 'node2.memo'} 0.9"

if runMultipleTimes:
    for i in range(1000):
        tl.time = tl.now() + 1e11
        node1.create_protocol('bsm_node', 'node2')
        node2.create_protocol('bsm_node', 'node1')
        pair_protocol(node1.protocols[0], node2.protocols[0])

        node1.memory.reset()
        node2.memory.reset()

        node1.protocols[0].start()
        node2.protocols[0].start()

        tl.init()
        print( 'tl.now() =', tl.now() )
        tl.run()

    print(node1.resource_manager.ent_counter, ':', node1.resource_manager.raw_counter)
    # (around 500:500; the exact number depends on the seed of numpy.random)
```
Thanks in advance...

**Comment by Alex-Kolar** [comment] 2021-01-14 07:22
Hi viachesl,
I found the issue. The tutorial and the example code should have the `Timeline.init()` method called before all protocols are started; as such, the single run of the entanglement protocol failed every time regardless of seed. I moved the init call before the start call, and it seems to be working.

P.S.: The `Timeline.seed()` method directly calls `np.random.seed`, so it is unnecessary to use both in your code.

**Comment by viachesl** [comment] 2021-01-14 23:07
> Hi viachesl,
> I found the issue. The tutorial and the example code should have the `Timeline.init()` method called before all protocols are started; as such, the single run of the entanglement protocol failed every time regardless of seed. I moved the init call before the start call, and it seems to be working.
> 
> P.S.: The `Timeline.seed()` method directly calls `np.random.seed`, so it is unnecessary to use both in your code.

Hi Alex,
I've tried before to move tl.init() before 
```
node1.protocols[0].start()
node2.protocols[0].start()
```
And it doesn't change the program behavior in my case. Did you try to run the code from my post with this fix and it gives different outputs from time to time due to seed depending on time?

**Comment by Alex-Kolar** [comment] 2021-01-14 23:59
Yes, the `init()` method is normally just called once at the beginning of simulation, after all simulation objects are created. This tutorial was written with the idea that we are performing multiple simulations of a single system, but I tested to confirm that the code still works if you remove the call within the loop. The only absolutely required `init` call is the one before the first two protocols are started. Does this answer your question?

**Comment by viachesl** [comment] 2021-01-15 20:36
Thank you, Alex for your answer. But my opinion is that only one init() call should be done at all cases. If special cases require force initialization of seed, maybe it's better to add to Timeline extra method, for instance, init_random_engines() doing necessary job and explain in the documentation when it must be called.

**Comment by xwu64** [comment] 2021-01-19 06:26
> Thank you, Alex for your answer. But my opinion is that only one init() call should be done at all cases. If special cases require force initialization of seed, maybe it's better to add to Timeline extra method, for instance, init_random_engines() doing necessary job and explain in the documentation when it must be called.

I think it's a good idea. Would you like to add this function for the class `Timeline`? You're welcomed to be an contributor of SeQUeNCe. 

The code of `Timeline` could be found by the link below.

https://github.com/sequence-toolbox/SeQUeNCe/blob/master/src/kernel/timeline.py

**Comment by viachesl** [comment] 2021-01-20 00:58
OK, I will think about that, but now I don't see how it can easily be implemented just by editing timeline.py. Probably, .start() function of Protocol should be corrected, because it brakes the seed, if I understand correctly.

**Comment by xwu64** [comment] 2021-01-20 04:39
> OK, I will think about that, but now I don't see how it can easily be implemented just by editing timeline.py. Probably, .start() function of Protocol should be corrected, because it brakes the seed, if I understand correctly.

Because we are using `numpy.random` to generate random number. Maybe you could use function `numpy.random.seed` to reset the seed of random number generator.

**Comment by caitaozhan** [comment] 2024-04-03 23:29
Nice discussion. I observe that the issue is solved and will close this issue soon.

**Closed** 2024-04-04 00:14 UTC
